apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: tekton-tools
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tekton-tools
    app.kubernetes.io/part-of: tekton-tools
  name: tekton-tools
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: tekton-tools
status:
  loadBalancer: {}
